general:
  bountyIncrease: 1
  emperorAmount: 4
  emperorThreshold: 1
  emperorTotal: 10
  recalculateLeaderboardIfVacant: false
files:
  emperorsFile: "EmperorsLeaderboardData.bin.gz"
commandsErrorMessages:
  noPlayer:
    - "&cInvalid command: &l%player%&c is offline or doesn't exist!"
  insufficientArguments:
    - "&cInvalid command: not enough arguments!"
  wrongSyntax:
    - "&cInvalid command: wrong syntax!"
  wrongType:
    - "&cInvalid command: &l%value%&c is not a &l%type%&c!"
  noPermission:
    - "&cYou aren't permitted to run this command!"
  bountyDisabled:
    - "&cPlayer &l%player_name%&c doesn't have a bounty!"
bountyCommand:
  messages:
    self:
      - "You have a bounty of &e&l$%piratebounties_bounty%"
    other:
      - "&e%player_name%&r has a bounty of &e&l$%piratebounties_bounty%"
setBountyCommand:
  messages:
    ok:
      - "Set &e%player_name%&r's bounty to &e&l$%piratebounties_bounty%"
emperorsCommand:
  messages:
    listHeader:
      - "The emperors are:"
    listLine:
      - "%index%. &e%player_name%&r, &e&l$%piratebounties_bounty%"
    offlineListLine:
      - "%index%. &e%player%&r, &e&l$%bounty%"
    noEmperors:
      - "&eThere are no emperors!"
      - "&rEarn at least &e&l$%piratebounties_emperors_thr%&r to become one!"
setEmperorsCommand:
  messages:
    ok:
      - "Leaderboard updated successfully"
