name: PirateBounties
version: "1.0.2"
main: com.github.photomultiplier.piratebounties.PirateBounties
api-version: "1.14"
commands:
  bounty:
    description: Fetch your or another player's bounty.
    usage: /<command> [<playername>]
  emperors:
    description: See who the emperors are.
    usage: /<command>
