name: PirateBounties
version: "1.5.1"
main: com.github.photomultiplier.piratebounties.PirateBounties
api-version: "1.14"
commands:
  bounty:
    description: Fetch your or another player's bounty.
    usage: /<command> [<playername>]
  setbounty:
    description: Set a player's bounty.
    usage: /<command> <playername> <new bounty>
  emperors:
    description: See who the emperors are.
    usage: /<command>
  setemperors:
    description: Edit the emperors leaderboard.
    usage: /<command> [update [<playername>] | remove <playername> | clear]
